<?php

namespace Nktlksvch\BulbaKit\DefaultCrud\Contracts;

use Nktlksvch\BulbaKit\DefaultCrud\DefaultCrudRegistry;

/**
 * Contract for default CRUD resources.
 *
 * Default CRUD resources are pre-built admin pages (migration, model, controller,
 * React pages, routes) that are automatically installed during `bulba:install`.
 * They follow the same structure as resources generated by `bulba:make`.
 *
 * Unlike modules, default resources are standardized CRUD operations with no
 * custom infrastructure (middleware, queues, etc.).
 *
 * @see DefaultCrudRegistry
 */
interface DefaultCrud
{
    /**
     * Display name (e.g., 'Website Settings').
     */
    public function name(): string;

    /**
     * Short description shown in the installer output.
     */
    public function description(): string;

    /**
     * Lucide icon name as string (e.g., 'settings').
     */
    public function icon(): string;

    /**
     * Eloquent model name (e.g., 'WebsiteSetting').
     */
    public function modelName(): string;

    /**
     * Database table name (e.g., 'website_settings').
     */
    public function tableName(): string;

    /**
     * Field definitions in the same format as bulba:make interactive input.
     *
     * @return array<int, array<string, mixed>>
     */
    public function fields(): array;

    /**
     * Controller methods to generate (e.g., ['index', 'create', 'store']).
     *
     * @return array<int, string>
     */
    public function controllerMethods(): array;

    /**
     * Generation options: timestamps, softDeletes.
     *
     * @return array<string, bool>
     */
    public function options(): array;

    /**
     * Navigation items for the sidebar.
     *
     * @return array<int, array{group: string, items: array<int, array{title: string, href: string, icon: string}>}>
     */
    public function navigation(): array;

    /**
     * Seeder class name (e.g., 'WebsiteSettingSeeder'), or null if no seeder.
     */
    public function seederClass(): ?string;

    /**
     * Seeder stub filename without extension, or null.
     */
    public function seederStub(): ?string;

    /**
     * Custom stubs that override standard generators.
     *
     * Supported keys:
     * - `index-page` — custom React index page (replaces standard generated Index.tsx)
     * - `controller-index` — custom index controller method (replaces standard inertia-index.stub)
     * - `controller-method` — additional controller method appended after standard methods
     *
     * Values: stub filename without `.stub` extension.
     *
     * @return array<string, string>
     */
    public function customStubs(): array;

    /**
     * Post-install hook for resource-specific setup (seeder registration, etc.).
     *
     * Called after all standard generators (migration, model, controller, pages, routes)
     * have completed. Use this for custom logic like registering seeders in DatabaseSeeder.
     *
     * @param  object  $command  The BulbaInstallCommand instance.
     */
    public function postInstall(object $command): void;
}
